//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Every refrigeration or air-conditioning system is different. Here at ECAC we understand that an off the shelf course will not suit everybody’s requirements and therefore we will design and deliver training to suit your unique requirements.&lt;/p&gt;
        ///&lt;/br&gt;
        ///&lt;p&gt;
        ///We will visit your site, discuss your requirements and examine your refrigeration or Air-conditioning equipment. We will then produce a first draft training outline which will be issued to you for approval. When the content has been agreed we will prod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BESPOKE_SERVICES_CONTENT {
            get {
                return ResourceManager.GetString("BESPOKE_SERVICE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Bespoke Course Design and Delivery&lt;/h1&gt;.
        /// </summary>
        internal static string BESPOKE_SERVICES_TITLE {
            get {
                return ResourceManager.GetString("BESPOKE_SERVICE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ECAC has a reputation for innovation and responsiveness to the requirements of Industry and the employees of Industry. We are aware that the days of a ‘job for life’ are a thing of the past and whether it be through choice or circumstances many people will change their job or employer many times over their lifetime.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///We have developed a range of services designed to meet the requirements of our clients who are dealing with a career change or are in the process of helping their employees to pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMPLOYABILITY_SERVICES_CONTENT {
            get {
                return ResourceManager.GetString("EMPLOYABILITY_SERVICES_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Employability Services&lt;/h1&gt;.
        /// </summary>
        internal static string EMPLOYABILITY_SERVICES_TITLE {
            get {
                return ResourceManager.GetString("EMPLOYABILITY_SERVICES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ECAC offers the full range of City &amp; Guilds 2079 Fgas training and certification. We are the main provider of these qualifications in the Irish market and have been offering City &amp; Guilds qualifications for over 10 years.  
        ///&lt;/p&gt;
        ///&lt;h2&gt;There are four levels in the qualification:&lt;/h2&gt;
        ///&lt;h3&gt;&lt;a href=&quot;$$FGAS_CAT1_LINK$$&quot;&gt;2079 100 (Cat 1)&lt;/a&gt;&lt;/h3&gt;
        ///&lt;p&gt;Successful candidates will be qualified to undertake leak checking, recovery, installation, service and maintenance of equipment.
        ///&lt;/p&gt;
        ///&lt;h3&gt;&lt;a href=&quot;$$FGAS_CAT2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FGAS_OVERVIEW_CONTENT {
            get {
                return ResourceManager.GetString("FGAS_OVERVIEW_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;City &amp; Guilds 2079 (F Gas) Qualifications&lt;/h1&gt;.
        /// </summary>
        internal static string FGAS_OVERVIEW_TITLE {
            get {
                return ResourceManager.GetString("FGAS_OVERVIEW_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;For candidates who have completed our Introduction to Refrigeration course we offer a more advanced program. We will build on your existing knowledge and experience to develop your fault finding and maintenance skills. This course includes an opportunity for candidates to install, commission and decommission a working vapour compression system under supervision.&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Recording operating conditions and parameters&lt;/li&gt;
        ///	&lt;li&gt;Analysing system conditions with a focus on predictive maintenance&lt;/li&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REFRIG_ADVANCED_CONTENT {
            get {
                return ResourceManager.GetString("REFRIG_ADVANCED_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Advanced Refrigeration Maintenance and Fault Finding&lt;/h1&gt;.
        /// </summary>
        internal static string REFRIG_ADVANCED_TITLE {
            get {
                return ResourceManager.GetString("REFRIG_ADVANCED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The following is an outline of our one day on site toolbox talk on R717 (Anhydrous Ammonia) safety course. This course is designed for all personnel who may come into contact with Anhydrous Ammonia refrigerant in the work place. It is designed to make all participants aware of the risks and safety procedures involved in handling R717.&lt;p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Overview of refrigerants (CFC, HCFC, HFC and Natural Refrigerants)&lt;/li&gt;
        ///	&lt;li&gt;Ammonia as a refrigerant, &lt;/li&gt;
        ///	&lt;li&gt;Flammability and toxicity&lt;/li&gt;
        ///	&lt;li&gt;Phys [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REFRIG_AMMONIA_CONTENT {
            get {
                return ResourceManager.GetString("REFRIG_AMMONIA_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;R717 Ammonia Safety Workshop(1 Day)&lt;/h1&gt;.
        /// </summary>
        internal static string REFRIG_AMMONIA_TITLE {
            get {
                return ResourceManager.GetString("REFRIG_AMMONIA_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;When you enrol on our Basic Refrigeration &amp; Air Conditioning program at ECAC, you will receive the training necessary to begin understanding the operation and function of the major components of the system and how to carry out basic maintenance and fault finding. 
        ///&lt;/p&gt;
        ///&lt;p&gt;The course is designed for tradesmen and technicians who’s duties put them in contact with refrigeration and HVAC plant.&lt;/p&gt;
        ///&lt;h3&gt;The course will cover various areas, including:&lt;/h3&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Basic Design and operation of the vapou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REFRIG_INTRO_CONTENT {
            get {
                return ResourceManager.GetString("REFRIG_INTRO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Introduction to Refrigeration&lt;/h1&gt;.
        /// </summary>
        internal static string REFRIG_INTRO_TITLE {
            get {
                return ResourceManager.GetString("REFRIG_INTRO_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Designed for candidates working with Industrial refrigeration systems but without any formal training in this area but have a good working knowledge or have completed an Introduction to Refrigeration training program.&lt;p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Refrigeration Systems Review&lt;/li&gt;
        ///	&lt;li&gt;Basic vapour compression cycle&lt;/li&gt;
        ///	&lt;li&gt;Pressure-enthalpy diagrams&lt;/li&gt;
        ///	&lt;li&gt;Influence of head pressure, suction pressure, sub cooling &amp; superheat &lt;/li&gt;
        ///	&lt;li&gt;System balance &lt;/li&gt;
        ///	&lt;li&gt;Condensers, types:  Air cooled, water-cooled, e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string REFRIG_LIQUID_CONTENT {
            get {
                return ResourceManager.GetString("REFRIG_LIQUID_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Liquid Overfeed Systems (3 Days)&lt;/h1&gt;.
        /// </summary>
        internal static string REFRIG_LIQUID_TITLE {
            get {
                return ResourceManager.GetString("REFRIG_LIQUID_TITLE", resourceCulture);
            }
        }
    }
}
