//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.Resources.Content", typeof(Content).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Every refrigeration or air-conditioning system is different. Here at ECAC we understand that an off the shelf course will not suit everybody’s requirements and therefore we will design and deliver training to suit your unique requirements.&lt;/p&gt;
        ///&lt;/br&gt;
        ///&lt;p&gt;
        ///We will visit your site, discuss your requirements and examine your refrigeration or Air-conditioning equipment. We will then produce a first draft training outline which will be issued to you for approval. When the content has been agreed we will prod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BESPOKE_SERVICE_CONTENT {
            get {
                return ResourceManager.GetString("BESPOKE_SERVICE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Bespoke Course Design and Delivery&lt;/h1&gt;.
        /// </summary>
        internal static string BESPOKE_SERVICE_TITLE {
            get {
                return ResourceManager.GetString("BESPOKE_SERVICE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ECAC has a reputation for innovation and responsiveness to the requirements of Industry and the employees of Industry. We are aware that the days of a ‘job for life’ are a thing of the past and whether it be through choice or circumstances many people will change their job or employer many times over their lifetime.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///We have developed a range of services designed to meet the requirements of our clients who are dealing with a career change or are in the process of helping their employees to pre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EMPLOYABILITY_SERVICES_CONTENT {
            get {
                return ResourceManager.GetString("EMPLOYABILITY_SERVICES_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Employability Services&lt;/h1&gt;.
        /// </summary>
        internal static string EMPLOYABILITY_SERVICES_TITLE {
            get {
                return ResourceManager.GetString("EMPLOYABILITY_SERVICES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;ECAC offers the full range of City &amp; Guilds 2079 Fgas training and certification. We are the main provider of these qualifications in the Irish market and have been offering City &amp; Guilds qualifications for over 10 years.  
        ///&lt;/p&gt;
        ///&lt;h2&gt;There are four levels in the qualification:&lt;/h2&gt;
        ///&lt;h3&gt;2079 100 (Cat 1)&lt;/h3&gt;
        ///&lt;p&gt;Successful candidates will be qualified to undertake leak checking, recovery, installation, service and maintenance of equipment.
        ///&lt;/p&gt;
        ///&lt;h3&gt;2079 200 (Cat 2)&lt;/h3&gt;
        ///&lt;p&gt;Successful candidates will  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FGAS_OVERVIEW_CONTENT {
            get {
                return ResourceManager.GetString("FGAS_OVERVIEW_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Cityy &amp; Guilds 2079 (F Gas) Qualifications&lt;/h1&gt;.
        /// </summary>
        internal static string FGAS_OVERVIEW_TITLE {
            get {
                return ResourceManager.GetString("FGAS_OVERVIEW_TITLE", resourceCulture);
            }
        }
    }
}
